# Install script for directory: E:/DONOTOPEN/FUCKYOU

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/CATFISH")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "0")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/LibJPEG/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/LibMNG/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/LibPNG/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/LibOpenJPEG/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/LibTIFF/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/OpenEXR/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/FreeImage/Source/ZLib/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/lua-5.2.2/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/GlesSyetem/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/IO/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/ResourcePhraser/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/ScriptSystem/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/SoundSystem/cmake_install.cmake")
  INCLUDE("E:/DONOTOPEN/FUCKYOU/ANDROID/CATFISH/DemoA/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "E:/DONOTOPEN/FUCKYOU/ANDROID/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "E:/DONOTOPEN/FUCKYOU/ANDROID/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
